# Netlify Configuration for BIZtech React App
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Command to run to build the site
  command = "npm ci && npm run build"
  
  # Base directory for the build
  base = "."

[build.environment]
  # Node.js version for build
  NODE_VERSION = "20.19.0"
  NPM_VERSION = "10"
  
  # Environment variables for build
  VITE_APP_NAME = "BIZtech"
  VITE_CONTACT_EMAIL = "ukrush12@gmail.com"
  VITE_ENABLE_CONTACT_FORM = "true"
  VITE_ENABLE_ANIMATIONS = "true"

# Redirect rules for Single Page Application (SPA)
# This ensures React Router works properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin", "editor"]}

# Security headers for enhanced protection
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    
    # Performance headers
    X-DNS-Prefetch-Control = "on"

# Cache optimization for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML files - shorter cache
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Contact form handling (if using Netlify Forms)
[forms]
  # Enable form processing
  netlify = true

# Function configuration (for future serverless functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.audits]
    performance = true
    accessibility = true
    best-practices = true
    seo = true

# Build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Context-specific settings
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "staging" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }